name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag leonardosartorello/seguranca_docker:${{ github.run_number }}

    - name: Docker Scout
      uses: docker/scout-action@v1.18.2
      with:
         command: quickview
         image: leonardosartorello/seguranca_docker:${{ github.run_number }}
         ignore-base: FALSE
         dockerhub-user: ${{secrets.DOCKERHUB_USERNAME}}
         dockerhub-password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.34.1
      with:
        scan-type: vuln
        image-ref: leonardosartorello/seguranca_docker:${{ github.run_number }}
        exit-code: 1
        severity: HIGH,CRITICAL
        format: table
          
          
